Fix authentication statement is too old to be used issue
Some IDPs cache user credentials for more than 2 hours causing
cbioportal to complain:
org.springframework.security.authentication.CredentialsExpiredException: Authentication statement is too old to be used with value 2022-04-08T13:53:25.502Z